import React from 'react';
import { Plus, Trash2 } from 'lucide-react';
export const newCheck = () => ({ id:crypto.randomUUID(), aspect:'', detail:'' });
export function CheckInputTable({ rows, onChange, disabled }) {
  const update = (id,key,value) => onChange(rows.map(r => r.id === id ? { ...r,[key]:value } : r));
  return <div className="check-editor"><div className="table-scroll" role="region" aria-label="Daftar pemeriksaan" tabIndex={0}><table className="checks-table"><caption className="sr-only">Hal yang ingin diperiksa dalam TOR</caption><thead><tr><th scope="col">No.</th><th scope="col">Aspek</th><th scope="col">Yang ingin diperiksa</th><th scope="col"><span className="sr-only">Tindakan</span></th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><th scope="row">{i+1}</th><td><input aria-label={`Aspek ${i+1}`} value={r.aspect} maxLength={100} disabled={disabled} placeholder="Mis. volume peserta" onChange={e=>update(r.id,'aspect',e.target.value)}/></td><td><textarea aria-label={`Pemeriksaan ${i+1}`} value={r.detail} maxLength={600} rows={2} disabled={disabled} placeholder="Mis. apakah jumlah peserta sesuai acuan?" onChange={e=>update(r.id,'detail',e.target.value)}/></td><td><button className="row-remove" disabled={disabled || rows.length===1} onClick={()=>onChange(rows.filter(x=>x.id!==r.id))} aria-label={`Hapus baris ${i+1}`}><Trash2 size={18}/></button></td></tr>)}</tbody></table></div><button className="button secondary" disabled={disabled || rows.length>=10} onClick={()=>onChange([...rows,newCheck()])}><Plus size={18}/> Tambah pemeriksaan</button></div>;
}
const labels={aligned:'Selaras',partial:'Sebagian selaras',discrepancy:'Ketidaksesuaian',insufficient:'Bukti belum cukup'};
export function ResultsTable({ findings }) {
  return <div className="table-scroll results-scroll" role="region" aria-label="Tabel hasil pemeriksaan" tabIndex={0}><table className="findings-table"><caption>Temuan, lokasi, dan perhitungan</caption><thead><tr><th scope="col">Aspek & status</th><th scope="col">Lokasi dalam TOR</th><th scope="col">Dasar acuan</th><th scope="col">Perhitungan & selisih</th><th scope="col">Penjelasan & tindak lanjut</th></tr></thead><tbody>{findings.map(f=><tr key={f.id}><th scope="row"><strong>{f.aspect}</strong><span className={`table-status ${f.status}`}>{labels[f.status]}</span></th><td><strong>{f.torLocation || 'Belum tersedia'}</strong><blockquote>{f.torQuote || 'Kutipan belum tersedia.'}</blockquote></td><td>{f.citations.length ? f.citations.map((c,i)=><details key={`${c.passageId}-${i}`}><summary>{c.title} · {c.location}</summary><p>{c.version}</p><blockquote>{c.quote}</blockquote>{/^https?:\/\//i.test(c.url || '') && <a href={c.url} target="_blank" rel="noreferrer">Buka sumber ↗</a>}</details>) : 'Acuan belum cukup.'}</td><td className="calculation-cell">{f.calculation || 'Tidak ada perhitungan numerik yang tersedia.'}</td><td><p>{f.reasoning}</p>{f.recommendation && <p><strong>Tindak lanjut:</strong> {f.recommendation}</p>}{f.checks.map(c=><p className="table-warning" key={c}>{c}</p>)}</td></tr>)}</tbody></table></div>;
}
