import React,{useState} from 'react';
import {proposalFields,urgencies,outputRows} from '../shared/workflow';
export const emptyProposal={programId:'',title:'',description:'',date:'',type:'Pelatihan',otherType:'',urgency:'',urgencyReason:'',ros:[],combined:true,tor:null,rab:null};
export const newOutput=()=>({id:crypto.randomUUID(),code:'',name:'',volume:'',unit:''});
export function OutputTable({rows}){return rows.length?<div className="wf-scroll"><table><thead><tr><th>RO</th><th>Volume</th><th>Satuan</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td>{r.code&&<span className="wf-cell-note">{r.code}</span>}{r.name}</td><td>{r.volume}</td><td>{r.unit}</td></tr>)}</tbody></table></div>:<span>Belum diisi</span>;}
export function ProgramForm({onSubmit,onCancel}){
  const [form,setForm]=useState({programName:'',programMission:'',programOutput:'',programTarget:''});
  return <form className="wf-card wf-form" onSubmit={e=>{e.preventDefault();onSubmit(form);}}><h2>Program baru</h2>{[['programName','Nama program',200],['programMission','Misi / tujuan program',3000],['programOutput','Output program',3000],['programTarget','Sasaran / penerima manfaat',1000]].map(([key,label,max])=><label key={key}>{label}<textarea rows={key==='programName'?1:2} required maxLength={max} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<div className="wf-actions"><button className="button primary" type="submit">Simpan program</button><button className="button secondary" type="button" onClick={onCancel}>Batal</button></div></form>;
}
export function ProgramTree({programs,items,onAdd,onOpen,rocan,states}){
  return <div className="wf-programs">{programs.map(p=>{const events=items.filter(s=>(s.programId||`legacy-${s.id}`)===p.id);return <section className="wf-card" key={p.id}><div className="wf-detail-title"><div><span className="wf-kicker">PROGRAM{rocan?` - ${p.satker}`:''}</span><h2>{p.programName}</h2></div>{!rocan&&<button className="button primary" onClick={()=>onAdd(p)}>Tambah kegiatan</button>}</div><details><summary>Tujuan dan sasaran program</summary><dl className="wf-proposal-summary">{[['Misi',p.programMission],['Output',p.programOutput],['Sasaran',p.programTarget]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details><h3 className="wf-events-heading">Kegiatan ({events.length})</h3>{events.length?<div className="wf-event-children">{events.map(s=><article className="wf-event-node" key={s.id}><div className="wf-detail-title"><h3>{s.title}</h3><span className={`wf-badge ${s.status}`}>{states[s.status]}</span></div><p>{s.date} · {urgencies[s.urgency]||'Kategori belum diisi'}</p><details><summary>Rincian Output ({outputRows(s).length})</summary><OutputTable rows={outputRows(s)}/></details><button className="wf-link" onClick={()=>onOpen(s.id)}>Buka pengajuan</button></article>)}</div>:<p>Belum ada kegiatan dalam program ini.</p>}</section>;})}{!programs.length&&<section className="wf-card"><h2>Belum ada program</h2><p>Buat program, lalu tambahkan pengajuan kegiatan di dalamnya.</p></section>}</div>;
}
export function ProposalForm({form,setField,submit,editing,selected,FileField,modePicker,screenMode,program}){
  const text=(key,label,max=200,multiline=false)=><label>{label}{multiline?<textarea required rows={3} maxLength={max} value={form[key]} onChange={e=>setField(key,e.target.value)}/>:<input required maxLength={max} value={form[key]} onChange={e=>setField(key,e.target.value)}/>}</label>;
  const updateRO=(id,key,value)=>setField('ros',form.ros.map(r=>r.id===id?{...r,[key]:value}:r));
  return <form className="wf-card wf-form" onSubmit={submit}><div className="wf-parent-program"><span className="wf-kicker">PROGRAM INDUK</span><h2>{program?.programName||form.programName}</h2><p>{program?.programMission||form.programMission}</p></div><h2>Pengajuan kegiatan</h2>
    {text('title','Nama kegiatan')}{text('description','Deskripsi dan tujuan kegiatan',5000,true)}<div className="wf-grid"><label>Tanggal kegiatan<input required type="date" value={form.date} onChange={e=>setField('date',e.target.value)}/></label><label>Jenis kegiatan<select value={form.type} onChange={e=>setField('type',e.target.value)}>{['Pelatihan','Rapat / koordinasi','Sosialisasi','Seminar','Kunjungan kerja','Lainnya'].map(t=><option key={t}>{t}</option>)}</select></label></div>{form.type==='Lainnya'&&text('otherType','Sebutkan jenis kegiatan (contoh: pendampingan teknis)')}
    <h2>Klasifikasi kegiatan</h2><label>Kategori urgensi<select required value={form.urgency} onChange={e=>setField('urgency',e.target.value)}><option value="">Pilih kategori</option>{Object.entries(urgencies).map(([value,label])=><option key={value} value={value}>{label}{value==='1'?' · paling rendah':value==='4'?' · paling tinggi':''}</option>)}</select></label>{text('urgencyReason','Alasan kategori dan dampak jika ditunda',3000,true)}
    <section className="wf-output-editor"><h2>Rincian Output kegiatan ({form.ros.length})</h2>{form.ros.map((r,i)=><fieldset className="wf-ro-card" key={r.id}><legend>RO {i+1}</legend><label>Kode RO {i+1} (opsional)<input maxLength={100} value={r.code} onChange={e=>updateRO(r.id,'code',e.target.value)}/></label><label>Nama RO {i+1}<input required maxLength={1000} value={r.name} onChange={e=>updateRO(r.id,'name',e.target.value)}/></label><div className="wf-grid"><label>Volume RO {i+1}<input required type="number" min="0.000001" step="any" value={r.volume} onChange={e=>updateRO(r.id,'volume',e.target.value)}/></label><label>Satuan RO {i+1}<input required maxLength={100} value={r.unit} onChange={e=>updateRO(r.id,'unit',e.target.value)} placeholder="orang, laporan, dokumen"/></label></div><button className="button secondary" type="button" disabled={form.ros.length===1} onClick={()=>setField('ros',form.ros.filter(row=>row.id!==r.id))}>Hapus RO {i+1}</button></fieldset>)}<button type="button" className="button secondary" disabled={form.ros.length>=100} onClick={()=>setField('ros',[...form.ros,newOutput()])}>Tambah RO</button></section>
    <h2>TOR dan RAB</h2><label>Susunan dokumen<select value={form.combined?'combined':'separate'} onChange={e=>setField('combined',e.target.value==='combined')}><option value="combined">TOR dan RAB dalam satu PDF</option><option value="separate">TOR dan RAB terpisah</option></select></label>{editing&&<p>Dokumen lama tetap digunakan jika tidak diganti.</p>}<div className="wf-grid"><FileField label={form.combined?'TOR + RAB':'TOR'} value={form.tor||(editing&&!(form.combined&&!selected?.combined)?selected?.tor:null)} onChange={v=>setField('tor',v)} required={!editing||(form.combined&&!selected?.combined)}/>{!form.combined&&<FileField label="RAB" value={form.rab||(editing?selected?.rab:null)} onChange={v=>setField('rab',v)} required={!editing||!selected?.rab}/>}</div><div className="wf-form-footer">{modePicker}<p>{screenMode==='real'?'TOR, RAB, dan acuan yang berlaku dikirim ke layanan AI.':'Simulasi: isi dokumen tidak dianalisis.'}</p><button className="button primary" type="submit">{editing?'Ajukan ulang & screening':'Kirim pengajuan & screening'}</button></div>
  </form>;
}
function valueLabel(field,value){if(field==='ros')return <OutputTable rows={Array.isArray(value)?value:[]}/>;if(value==null||value==='')return 'Belum diisi';if(field==='combined')return value?'TOR + RAB satu PDF':'TOR dan RAB terpisah';if(field==='urgency')return urgencies[value]||value;return String(value);}
export function ProposalSummary({proposal,all=false}){return <dl className="wf-proposal-summary">{Object.entries(proposalFields).filter(([k])=>all||!['title','description','date','type','otherType','combined'].includes(k)).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{valueLabel(key,key==='ros'?outputRows(proposal):proposal[key])}</dd></div>)}</dl>;}
export function VersionViewer({submission,download}){
  const versions=submission.versions||[],[number,setNumber]=useState(versions.at(-1)?.number),[showAll,setShowAll]=useState(false);
  const version=versions.find(v=>v.number===number);if(!version)return null;
  return <section className="wf-card"><h2>Versi pengajuan</h2><label>Pilih versi<select value={number} onChange={e=>setNumber(Number(e.target.value))}>{[...versions].reverse().map(v=><option key={v.number} value={v.number}>Versi {v.number} · {new Date(v.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</option>)}</select></label><p>{version.by} · {new Date(version.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p>{version.legacy&&<p>Snapshot awal dari data lama. Perubahan sebelum fitur versi tersedia tidak terekam.</p>}
    {version.number===1?<p>Versi awal yang tersimpan.</p>:version.changes.length?<div className="wf-scroll" tabIndex={0} role="region" aria-label="Perubahan antarversi"><table><caption>Perubahan versi {version.number-1} → {version.number}</caption><thead><tr><th>Bagian</th><th>Sebelumnya</th><th>Versi ini</th></tr></thead><tbody>{version.changes.map(c=><tr key={c.field}><th>{proposalFields[c.field]||c.field.toUpperCase()}</th><td className="wf-version-value">{valueLabel(c.field,c.before)}</td><td className="wf-version-value">{valueLabel(c.field,c.after)}{c.replaced&&<span className="wf-cell-note">Isi PDF diganti</span>}</td></tr>)}</tbody></table></div>:<p>Diajukan ulang tanpa perubahan isi.</p>}
    <div className="wf-actions"><button type="button" className="button secondary" aria-expanded={showAll} onClick={()=>setShowAll(!showAll)}>{showAll?'Tutup isi versi':'Lihat seluruh isi versi'}</button>{['tor','rab'].filter(k=>version.proposal[k]).map(kind=><button key={kind} className="button secondary" onClick={()=>download(`submissions/${submission.id}/file?kind=${kind}&version=${version.number}`)}>Unduh {kind==='tor'&&version.proposal.combined?'TOR + RAB':kind.toUpperCase()} · v{version.number}</button>)}</div>{showAll&&<ProposalSummary proposal={version.proposal} all/>}
  </section>;
}
