import React,{useState,useRef,useEffect} from 'react';
import {proposalFields,urgencies} from '../shared/workflow';

export const emptyProposal={programName:'',programMission:'',programOutput:'',programTarget:'',title:'',description:'',date:'',type:'Pelatihan',otherType:'',urgency:'',urgencyReason:'',roCode:'',roName:'',roVolume:'',roUnit:'',combined:true,tor:null,rab:null};
const steps=['Program','Kegiatan','Klasifikasi','RO'];
export function ProposalForm({form,setField,submit,editing,selected,FileField,modePicker,screenMode}){
  const [step,setStep]=useState(0),heading=useRef(null);
  useEffect(()=>{heading.current?.focus();},[step]);
  const text=(key,label,max=200,multiline=false)=><label>{label}{multiline?<textarea required rows={3} maxLength={max} value={form[key]} onChange={e=>setField(key,e.target.value)}/>:<input required maxLength={max} value={form[key]} onChange={e=>setField(key,e.target.value)}/>}</label>;
  function advance(e){e.preventDefault();if(step<3){setStep(step+1);return;}submit(e);}
  return <form className="wf-card wf-form" onSubmit={advance}>
    <ol className="wf-steps" aria-label="Tahap pengajuan">{steps.map((name,i)=><li key={name} aria-current={i===step?'step':undefined}><span>{i+1}</span>{name}</li>)}</ol>
    <h2 tabIndex={-1} ref={heading}>Langkah {step+1}: {steps[step]==='RO'?'Rincian Output (RO)':steps[step]}</h2>
    {step===0&&<>{text('programName','Nama program')}{text('programMission','Misi / tujuan program',3000,true)}{text('programOutput','Output yang ingin dicapai',3000,true)}{text('programTarget','Sasaran / penerima manfaat',1000)}</>}
    {step===1&&<>{text('title','Nama kegiatan')}{text('description','Deskripsi dan tujuan kegiatan',5000,true)}<div className="wf-grid"><label>Tanggal kegiatan<input required type="date" value={form.date} onChange={e=>setField('date',e.target.value)}/></label><label>Jenis kegiatan<select value={form.type} onChange={e=>setField('type',e.target.value)}>{['Pelatihan','Rapat / koordinasi','Sosialisasi','Seminar','Kunjungan kerja','Lainnya'].map(t=><option key={t}>{t}</option>)}</select></label></div>{form.type==='Lainnya'&&text('otherType','Sebutkan jenis kegiatan (contoh: pengajian)')}<h2>TOR dan RAB</h2><label>Susunan dokumen<select value={form.combined?'combined':'separate'} onChange={e=>setField('combined',e.target.value==='combined')}><option value="combined">TOR dan RAB dalam satu PDF</option><option value="separate">TOR dan RAB terpisah</option></select></label>{editing&&<p>Dokumen lama tetap digunakan jika tidak diganti.</p>}<div className="wf-grid"><FileField label={form.combined?'TOR + RAB':'TOR'} value={form.tor||(editing&&!(form.combined&&!selected?.combined)?selected?.tor:null)} onChange={v=>setField('tor',v)} required={!editing||(form.combined&&!selected?.combined)}/>{!form.combined&&<FileField label="RAB" value={form.rab||(editing?selected?.rab:null)} onChange={v=>setField('rab',v)} required={!editing||!selected?.rab}/>}</div>{editing&&form.combined&&!selected?.combined&&!form.tor&&<p role="alert">Unggah PDF gabungan baru yang memuat TOR dan RAB.</p>}</>}
    {step===2&&<><label>Kategori urgensi<select required value={form.urgency} onChange={e=>setField('urgency',e.target.value)}><option value="">Pilih kategori</option>{Object.entries(urgencies).map(([value,label])=><option key={value} value={value}>{label}{value==='1'?' · paling rendah':value==='4'?' · paling tinggi':''}</option>)}</select></label><p>Kategori 1 → 2 → 3 → 4: semakin tinggi, semakin mendesak untuk dilaksanakan.</p>{text('urgencyReason','Alasan kategori dan dampak jika ditunda',3000,true)}</>}
    {step===3&&<><label>Kode RO (opsional)<input maxLength={100} value={form.roCode} onChange={e=>setField('roCode',e.target.value)}/></label>{text('roName','Nama Rincian Output',1000)}<div className="wf-grid"><label>Volume target<input required type="number" min="0.000001" step="any" value={form.roVolume} onChange={e=>setField('roVolume',e.target.value)}/></label>{text('roUnit','Satuan (contoh: orang, laporan)',100)}</div><details><summary>Tinjau pengajuan sebelum dikirim</summary><ProposalSummary proposal={form} all/></details><div className="wf-form-footer">{modePicker}<p>{screenMode==='real'?'TOR, RAB, dan acuan yang berlaku dikirim ke layanan AI.':'Simulasi: isi dokumen tidak dianalisis.'}</p></div></>}
    <div className="wf-step-actions">{step>0&&<button type="button" className="button secondary" onClick={()=>setStep(step-1)}>Kembali</button>}<button className="button primary" type="submit">{step<3?`Lanjut: ${steps[step+1]}`:editing?'Ajukan ulang & screening':'Kirim pengajuan & screening'}</button></div>
  </form>;
}
function valueLabel(field,value){if(value==null||value==='')return 'Belum diisi';if(field==='combined')return value?'TOR + RAB satu PDF':'TOR dan RAB terpisah';if(field==='urgency')return urgencies[value]||value;return String(value);}
export function ProposalSummary({proposal,all=false}){return <dl className="wf-proposal-summary">{Object.entries(proposalFields).filter(([k])=>all||!['title','description','date','type','otherType','combined'].includes(k)).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{valueLabel(key,proposal[key])}</dd></div>)}</dl>;}
export function VersionViewer({submission,download}){
  const versions=submission.versions||[],[number,setNumber]=useState(versions.at(-1)?.number),[showAll,setShowAll]=useState(false);
  const version=versions.find(v=>v.number===number);if(!version)return null;
  return <section className="wf-card"><h2>Versi pengajuan</h2><label>Pilih versi<select value={number} onChange={e=>setNumber(Number(e.target.value))}>{[...versions].reverse().map(v=><option key={v.number} value={v.number}>Versi {v.number} · {new Date(v.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</option>)}</select></label><p>{version.by} · {new Date(version.at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p>{version.legacy&&<p>Snapshot awal dari data lama. Perubahan sebelum fitur versi tersedia tidak terekam.</p>}
    {version.number===1?<p>Versi awal yang tersimpan.</p>:version.changes.length?<div className="wf-scroll" tabIndex={0} role="region" aria-label="Perubahan antarversi"><table><caption>Perubahan versi {version.number-1} → {version.number}</caption><thead><tr><th>Bagian</th><th>Sebelumnya</th><th>Versi ini</th></tr></thead><tbody>{version.changes.map(c=><tr key={c.field}><th>{proposalFields[c.field]||c.field.toUpperCase()}</th><td className="wf-version-value">{valueLabel(c.field,c.before)}</td><td className="wf-version-value">{valueLabel(c.field,c.after)}{c.replaced&&<span className="wf-cell-note">Isi PDF diganti</span>}</td></tr>)}</tbody></table></div>:<p>Diajukan ulang tanpa perubahan isi.</p>}
    <div className="wf-actions"><button type="button" className="button secondary" aria-expanded={showAll} onClick={()=>setShowAll(!showAll)}>{showAll?'Tutup isi versi':'Lihat seluruh isi versi'}</button>{['tor','rab'].filter(k=>version.proposal[k]).map(kind=><button key={kind} className="button secondary" onClick={()=>download(`submissions/${submission.id}/file?kind=${kind}&version=${version.number}`)}>Unduh {kind==='tor'&&version.proposal.combined?'TOR + RAB':kind.toUpperCase()} · v{version.number}</button>)}</div>{showAll&&<ProposalSummary proposal={version.proposal} all/>}
  </section>;
}
