import React,{useEffect,useState} from 'react';
import {ListChecks,ClipboardList,BookOpen,Plus,ArrowLeft,LogOut,RefreshCw,Download,CheckCircle2,Clock,FileText} from 'lucide-react';
import ThemeToggle from './ThemeToggle';
import './workflow.css';
import {pagesApi} from './pages-api';
import {ProposalForm,ProposalSummary,VersionViewer,emptyProposal} from './ProposalFlow';
const pagesDemo=import.meta.env.VITE_PAGES_DEMO;

const states={pending_screening:'Menunggu screening',needs_revision:'Perlu perbaikan',queued:'Menunggu Rocan',manual_review:'Perlu telaah manual',approved:'Disetujui',rejected:'Ditolak'};
const findingLabels={aligned:'Selaras',partial:'Sebagian selaras',discrepancy:'Ketidaksesuaian',insufficient:'Bukti belum cukup'};
const dateLabel=v=>new Date(v).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'});
const dateKey=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
const emptyForm=emptyProposal;
async function readPdf(file) {
  if(!file)return null;
  if(!file.name.toLowerCase().endsWith('.pdf')||file.size>10*1024*1024)throw Error('Gunakan PDF maksimum 10 MB.');
  const bytes=new Uint8Array(await file.arrayBuffer());
  if(!new TextDecoder().decode(bytes.slice(0,1024)).includes('%PDF-'))throw Error('Berkas bukan PDF yang valid.');
  let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));
  return {name:file.name,data:btoa(binary)};
}
function Badge({status}) {return <span className={`wf-badge ${status}`}>{states[status]||status}</span>;}
function FileField({label,value,onChange,required=true}) {
  const [error,setError]=useState(''),[reading,setReading]=useState(false);
  return <label className="wf-file">{label}<input type="file" accept=".pdf,application/pdf" required={required&&!value} disabled={reading} onChange={async e=>{const f=e.target.files?.[0];setError('');setReading(true);try{onChange(await readPdf(f));}catch(err){setError(err.message);onChange(null);e.target.value='';}finally{setReading(false);}}}/><span>{reading?'Membaca berkas…':value?.name||'PDF · maksimum 10 MB'}</span>{error&&<span role="alert" className="wf-error">{error}</span>}</label>;
}
export default function WorkflowApp({user,onLogout}) {
  const rocan=user.role==='rocan';
  const [view,setView]=useState('list'),[items,setItems]=useState([]),[docs,setDocs]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState({satker:'',from:'',to:'',status:''}),[order,setOrder]=useState('newest'),[screenMode,setScreenMode]=useState(pagesDemo?'pass':'real');
  async function api(path,method='GET',body) {if(pagesDemo)return pagesApi(user,path,method,body);const response=await fetch(`/api/workflow/${path}`,{method,headers:{'Content-Type':'application/json','X-Telaah-Profile':encodeURIComponent(JSON.stringify(user))},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Permintaan gagal.');return data;}
  async function refresh(){setItems(await api('submissions'));if(rocan)setDocs(await api('references'));}
  async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{act(refresh);},[]);
  async function open(id){await act(async()=>{setSelected(await api(`submissions/${id}`));setView('detail');});}
  async function screening(s){
    try {setSelected(await api(`submissions/${s.id}/screen`,'POST',{demo:screenMode!=='real',scenario:screenMode==='revision'?'revision':'pass'}));}
    finally {await refresh();}
  }
  async function submit(e){e.preventDefault();await act(async()=>{const s=await api(editing?`submissions/${editing}`:'submissions',editing?'PUT':'POST',form);setSelected(s);setView('detail');setEditing(null);await screening(s);});}
  async function download(path){await act(async()=>{const f=await api(path),bytes=Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
  function newForm(s){setForm(s?{...emptyForm,...s,tor:null,rab:null}:emptyForm);setEditing(s?.id||null);setView('form');setError('');setScreenMode(pagesDemo?'pass':'real');}
  const visible=items.filter(s=>(!filter.satker||s.satker===filter.satker)&&(!filter.status||s.status===filter.status)&&(!filter.from||dateKey(s.createdAt)>=filter.from)&&(!filter.to||dateKey(s.createdAt)<=filter.to)).sort((a,b)=>order==='newest'?b.createdAt.localeCompare(a.createdAt):a.createdAt.localeCompare(b.createdAt));
  const setField=(key,value)=>setForm(f=>({...f,[key]:value}));
  const modePicker=<label>Screening<select value={screenMode} onChange={e=>setScreenMode(e.target.value)}>{!pagesDemo&&<option value="real">AI · dokumen sebenarnya</option>}<option value="pass">Simulasi · lanjut ke Rocan</option><option value="revision">Simulasi · perlu perbaikan</option></select></label>;
  return <div className="wf-app ai-workspace"><aside className="wf-sidebar"><a className="brand" href="#" onClick={()=>setView('list')}><span className="brand-icon"><ListChecks size={24}/></span>telaah<span className="brand-dot">.</span></a><div className="wf-assistant">Asisten Perencanaan</div><nav aria-label="Navigasi utama"><button className={view!=='refs'?'active':''} onClick={()=>setView('list')}><ClipboardList size={20}/>{rocan?'Semua pengajuan':'Pengajuan saya'}</button>{rocan&&<button className={view==='refs'?'active':''} onClick={()=>setView('refs')}><BookOpen size={20}/>Dokumen acuan</button>}</nav><div className="wf-account"><strong>{user.name}</strong><span>{rocan?'Rocan':user.satker}</span><span className="wf-badge">{rocan?'Peninjau':'Pengusul'} · mockup</span></div></aside><div className="wf-main"><header className="wf-top"><span>{rocan?'Ruang Rocan':'Ruang Satker'}</span><div><ThemeToggle/><button className="wf-icon" disabled={busy} onClick={onLogout} aria-label="Keluar"><LogOut size={20}/></button></div></header><main className="wf-content"><div className="wf-heading"><div><p className="wf-kicker">PERENCANAAN KEGIATAN</p><h1>{view==='refs'?'Dokumen acuan':view==='form'?(editing?'Perbaiki pengajuan':'Ajukan kegiatan'):view==='detail'?'Detail pengajuan':rocan?'Antrean pengajuan':'Pengajuan kegiatan'}</h1></div><div className="wf-actions">{view==='list'&&<><button className="button secondary" disabled={busy} onClick={()=>act(refresh)} aria-label="Muat ulang"><RefreshCw size={18}/></button>{!rocan&&<button className="button primary" onClick={()=>newForm()}><Plus size={18}/>Ajukan kegiatan</button>}</>}{['detail','form'].includes(view)&&<button className="button secondary" disabled={busy} onClick={()=>setView('list')}><ArrowLeft size={18}/>Daftar pengajuan</button>}</div></div>
      {error&&<div className="wf-alert wf-error" role="alert">{error}</div>}{notice&&<div className="wf-alert" role="status">{notice}</div>}{busy&&<div className="wf-alert" role="status">Memproses… Pengajuan dan screening dapat memerlukan waktu.</div>}
      {pagesDemo&&<div className="wf-alert">Demo GitHub Pages · screening simulasi. Data dan PDF hanya tersimpan di browser ini, tidak dibagikan antarperangkat.</div>}<fieldset className="wf-body" disabled={busy}>
      {view==='list'&&<><div className="wf-stats">{[[ClipboardList,'Total pengajuan',items.length],[Clock,'Menunggu Rocan',items.filter(s=>['queued','manual_review'].includes(s.status)).length],[CheckCircle2,'Disetujui',items.filter(s=>s.status==='approved').length]].map(([Icon,label,value])=><div key={label}><Icon size={23}/><span>{label}</span><strong>{value}</strong></div>)}</div><section className="wf-card"><div className="wf-filters">{rocan&&<label>Satker<select value={filter.satker} onChange={e=>setFilter({...filter,satker:e.target.value})}><option value="">Semua Satker</option>{[...new Set(items.map(s=>s.satker))].sort().map(s=><option key={s}>{s}</option>)}</select></label>}<label>Diajukan mulai<input type="date" value={filter.from} onChange={e=>setFilter({...filter,from:e.target.value})}/></label><label>Sampai<input type="date" min={filter.from} value={filter.to} onChange={e=>setFilter({...filter,to:e.target.value})}/></label><label>Status<select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">Semua status</option>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Urutan<select value={order} onChange={e=>setOrder(e.target.value)}><option value="newest">Terbaru</option><option value="oldest">Terlama</option></select></label><button className="button secondary" onClick={()=>setFilter({satker:'',from:'',to:'',status:''})}>Reset</button></div><div className="wf-scroll" tabIndex={0} role="region" aria-label="Tabel data"><table><thead><tr><th>Kegiatan</th>{rocan&&<th>Satker</th>}<th>Diajukan</th><th>Tanggal kegiatan</th><th>Status</th><th><span className="sr-only">Tindakan</span></th></tr></thead><tbody>{visible.map(s=><tr key={s.id}><td><strong>{s.title}</strong><span className="wf-cell-note">{s.type==='Lainnya'?`Lainnya — ${s.otherType||'belum dirinci'}`:s.type}{s.isSimulation?' · SIMULASI':''}</span></td>{rocan&&<td>{s.satker}</td>}<td>{dateLabel(s.createdAt)}</td><td>{dateLabel(s.date)}</td><td><Badge status={s.status}/></td><td><button className="wf-link" onClick={()=>open(s.id)}>Buka →</button></td></tr>)}</tbody></table></div>{!visible.length&&<div className="wf-empty"><ClipboardList size={36}/><h2>{items.length?'Tidak ada hasil filter':'Belum ada pengajuan'}</h2><p>{items.length?'Ubah filter untuk melihat pengajuan.':rocan?'Pengajuan Satker akan tampil di sini.':'Mulai dengan mengunggah TOR dan RAB kegiatan.'}</p></div>}</section></>}
      {view==='form'&&<ProposalForm form={form} setField={setField} submit={submit} editing={editing} selected={selected} FileField={FileField} modePicker={modePicker} screenMode={screenMode}/>}
      {view==='detail'&&selected&&<><section className="wf-card"><div className="wf-detail-title"><div><span className="wf-kicker">{selected.satker}</span><h2>{selected.title}</h2></div><Badge status={selected.status}/></div><div className="wf-meta"><span>{selected.type==='Lainnya'?`Lainnya — ${selected.otherType||'belum dirinci'}`:selected.type}</span><span>Kegiatan: {dateLabel(selected.date)}</span><span>Diajukan: {dateLabel(selected.createdAt)}</span></div><p className="wf-description">{selected.description}</p><ProposalSummary proposal={selected}/><div className="wf-actions"><button className="button secondary" onClick={()=>download(`submissions/${selected.id}/file?kind=tor`)}><Download size={17}/>{selected.combined?'TOR + RAB':'TOR'}</button>{selected.rab&&<button className="button secondary" onClick={()=>download(`submissions/${selected.id}/file?kind=rab`)}><Download size={17}/>RAB</button>}{!rocan&&['needs_revision','pending_screening'].includes(selected.status)&&<button className="button primary" onClick={()=>newForm(selected)}>Perbaiki pengajuan</button>}</div></section>
      {selected.status==='pending_screening'&&<section className="wf-card"><h2>Screening belum selesai</h2><p>{selected.screeningError||'Pengajuan tersimpan dan menunggu screening.'}</p><div className="wf-actions">{modePicker}<button className="button primary" onClick={()=>act(()=>screening(selected))}>Jalankan screening</button></div></section>}
      {selected.screening&&<ScreeningTable screening={selected.screening} rocan={rocan}/>}
      {rocan&&['queued','manual_review'].includes(selected.status)&&<DecisionForm onSubmit={body=>act(async()=>{setSelected(await api(`submissions/${selected.id}/decision`,'POST',body));await refresh();setNotice('Keputusan tersimpan.');})}/>}
      {selected.decision&&<section className="wf-card"><h2>Keputusan Rocan</h2><Badge status={selected.decision.status}/><p>{selected.decision.note}</p><p>{selected.decision.by} · {dateLabel(selected.decision.at)}</p></section>}
      <VersionViewer key={`${selected.id}-${selected.versions?.length}`} submission={selected} download={download}/><details className="wf-card"><summary>Riwayat proses & keputusan</summary><ol className="wf-history">{selected.history.map((h,i)=><li key={i}><strong>{states[h.action]||h.action}</strong> · {h.by} · {new Date(h.at).toLocaleString('id-ID')}{h.note&&<p>{h.note}</p>}</li>)}</ol></details></>}
      {view==='refs'&&rocan&&<ReferenceLibrary docs={docs} api={api} act={act} refresh={refresh} download={download}/>}
      </fieldset></main></div></div>;
}
function ScreeningTable({screening:s,rocan}) {return <section className="wf-card"><div className="wf-detail-title"><h2>{rocan?'Hasil screening':'Catatan screening'}</h2>{rocan&&<span className="wf-confidence">Confidence {s.confidence==null?'belum tersedia':`${s.confidence}%`}</span>}</div>{s.demo&&<div className="wf-alert">SIMULASI · hasil contoh, bukan analisis dokumen unggahan.</div>}{!s.demo&&<p>{s.summary}</p>}{rocan&&<><p>Keselarasan indikatif: <strong>{s.alignment==null?'Belum tersedia':`${s.alignment}%`}</strong> · Cakupan bukti: {s.coverage??'—'}%</p><details className="wf-method"><summary>Arti indikator</summary><p>Keselarasan: rata-rata selaras 100, sebagian 50, tidak sesuai 0; bukti belum cukup dikecualikan. Confidence adalah estimasi AI, bukan peluang kebenaran terkalibrasi. Kutipan PDF dan perhitungan perlu diverifikasi Rocan.</p></details></>}{s.findings.length?<div className="wf-scroll" tabIndex={0} role="region" aria-label="Tabel data"><table className="wf-findings"><thead><tr><th>Aspek / status</th><th>Lokasi & masalah</th><th>Acuan</th><th>Perhitungan & perbaikan</th>{rocan&&<th>Confidence AI</th>}</tr></thead><tbody>{s.findings.map((f,i)=><tr key={i}><td><strong>{f.aspect}</strong><span className={`wf-badge ${f.status}`}>{findingLabels[f.status]}</span>{f.severity==='fatal'&&<span className="wf-cell-note">Perlu diperbaiki sebelum diteruskan</span>}</td><td><strong>{f.location}</strong><blockquote>{f.quote}</blockquote><p>{f.reason}</p></td><td>{f.references.length?f.references.map((r,j)=><details key={j}><summary>{r.title} · {r.location}</summary><blockquote>{r.quote}</blockquote></details>):'Bukti acuan belum tersedia'}</td><td><pre>{f.calculation}</pre><p>{f.correction}</p></td>{rocan&&<td><strong>{f.confidence==null?'Belum dapat dinilai':`${f.confidence}%`}</strong></td>}</tr>)}</tbody></table></div>:<p>Tidak ada catatan perbaikan dari screening awal.</p>}{rocan&&s.references?.length>0&&<details><summary>Acuan yang digunakan ({s.references.length})</summary><ul>{s.references.map(d=><li key={d.id}>{d.title} · {d.start} — {d.end||'tanpa batas akhir'}</li>)}</ul></details>}</section>;}
function DecisionForm({onSubmit}) {const [decision,setDecision]=useState('approved'),[note,setNote]=useState(''),[checked,setChecked]=useState(false);return <form className="wf-card wf-form" onSubmit={e=>{e.preventDefault();onSubmit({decision,note});}}><h2>Keputusan Rocan</h2><label>Keputusan<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="approved">Setujui kegiatan</option><option value="needs_revision">Kembalikan untuk perbaikan</option><option value="rejected">Tolak kegiatan</option></select></label><label>Catatan keputusan<textarea required maxLength={3000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Alasan dan tindak lanjut untuk Satker"/></label><label className="wf-checkbox"><input type="checkbox" required checked={checked} onChange={e=>setChecked(e.target.checked)}/>Saya telah meninjau dokumen dan hasil screening.</label><button className="button primary" type="submit">Simpan keputusan</button></form>;}
function ReferenceLibrary({docs,api,act,refresh,download}) {
  const empty={title:'',type:'Renstra',start:'',end:'',enabled:true,file:null};const [form,setForm]=useState(empty),[editing,setEditing]=useState(null),[show,setShow]=useState(false);
  const field=(k,v)=>setForm(f=>({...f,[k]:v}));
  return <><div className="wf-library-header"><p>Acuan dipilih sesuai tanggal kegiatan dan status aktif.</p><button className="button primary" onClick={()=>{setShow(true);setEditing(null);setForm(empty);}}><Plus size={18}/>Tambah acuan</button></div>{show&&<form className="wf-card wf-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api(editing?`references/${editing}`:'references',editing?'PATCH':'POST',form);await refresh();setShow(false);});}}><h2>{editing?'Ubah acuan':'Dokumen acuan baru'}</h2><label>Judul acuan<input required maxLength={200} value={form.title} onChange={e=>field('title',e.target.value)}/></label><label>Jenis<select value={form.type} onChange={e=>field('type',e.target.value)}>{['RPJMN','Renstra','Permen','Perpres','Standar biaya','Lainnya'].map(t=><option key={t}>{t}</option>)}</select></label><div className="wf-grid"><label>Berlaku mulai<input required type="date" value={form.start} onChange={e=>field('start',e.target.value)}/></label><label>Berlaku sampai (opsional)<input type="date" min={form.start} value={form.end||''} onChange={e=>field('end',e.target.value)}/></label></div><p>Kosongkan tanggal akhir jika belum ditentukan.</p>{!editing&&<FileField label="PDF acuan" value={form.file} onChange={v=>field('file',v)}/>}<label className="wf-checkbox"><input type="checkbox" checked={form.enabled} onChange={e=>field('enabled',e.target.checked)}/>Izinkan penggunaan sesuai periode</label><div className="wf-actions"><button type="submit" className="button primary">Simpan acuan</button><button type="button" className="button secondary" onClick={()=>setShow(false)}>Batal</button></div></form>}<section className="wf-card"><div className="wf-scroll" tabIndex={0} role="region" aria-label="Tabel data"><table><thead><tr><th>Dokumen</th><th>Masa berlaku</th><th>Status hari ini</th><th>Penggunaan</th><th>Tindakan</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><strong>{d.title}</strong><span className="wf-cell-note">{d.type}</span></td><td>{dateLabel(d.start)} — {d.end?dateLabel(d.end):'Tanpa batas akhir'}</td><td><span className={`wf-badge ${d.activeNow?'approved':''}`}>{d.activeNow?'Aktif':!d.enabled?'Dinonaktifkan':d.start>dateKey(new Date())?'Belum berlaku':'Berakhir'}</span></td><td><button className="button secondary" onClick={()=>act(async()=>{await api(`references/${d.id}`,'PATCH',{enabled:!d.enabled});await refresh();})}>{d.enabled?'Nonaktifkan':'Aktifkan'}</button></td><td><div className="wf-actions"><button className="wf-link" onClick={()=>{setForm({...d,file:null});setEditing(d.id);setShow(true);}}>Ubah periode</button><button className="wf-icon" aria-label={`Unduh ${d.title}`} onClick={()=>download(`references/${d.id}/file`)}><Download size={18}/></button></div></td></tr>)}</tbody></table></div>{!docs.length&&<div className="wf-empty"><BookOpen size={36}/><h2>Belum ada dokumen acuan</h2><p>Tambahkan RPJMN, Renstra, atau ketentuan pendukung lainnya.</p></div>}</section></>;
}
